#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from turkish.deasciifier import Deasciifier

class Deasciify:
    """
    This is the commandline utility for deasciification.

    Example usage:

    $ echo "Opusmegi cagristiran catirtilar." | turkish-deasciify
    $ cat somefile.txt | turkish-deasciify
    """


    def deasciify(self):
        string = sys.stdin.read()
        dea = Deasciifier(string)
        result = dea.convert_to_turkish()
        sys.stdout.write(result)

if __name__ == "__main__":
    d = Deasciify()
    d.deasciify()
